name: Hexo Deploy 

# 触发条件：在 push 到 main分支后
on:
  push:
    branches:
      - main
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master # 使用专门部署 Hexo 到 GitHub pages 的 action
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }} # secret 名
          PUBLISH_REPOSITORY: LJYXG/LJYXG.github.io # 公共仓库，格式：GitHub 用户名/仓库名
          BRANCH: test # 分支，填 gh-pages 就行
          PUBLISH_DIR: ./public # 部署 public 目录下的文件

