name: Hexo Deploy 

# 触发条件：在 push 到 main分支后
on:
  push:
    branches:
      - main
    # 只有下列文件的变更才会触发部署！！！！
    paths:
      - '**.md'
    # paths-ignore: # 下列文件的变更不触发部署，可以自行添加
    #   - README.md
    #   - LICENSE

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-20.04
    steps:
      #初始化 Node.js 环境
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 拉取代码
      - name: Checkout Main Files
        uses: actions/checkout@v3
        with:
          ref: main

      # 拉取主题代码
      - name: Checkout Themes 
        uses: actions/checkout@v3
        with:
          repository: /LJYXG/LJYXG.github.io
          ref: themes
          path: themes/stun
      
      # 建立 Hexo 环境
      - name: npm install hexo
        run: |
          npm install hexo-cli -g
          npm install hexo-deployer-git --save
          npm install --save hexo-renderer-pug 
        env:
          CI: true
      
      # 生成
      - name: Hexo Build
        run: |
          hexo clean
          hexo g
      

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./public
